// Generates the skill catalogs (ADR-0002):
//   INDEX.md                     — repo-facing catalog of every pack and skill
//   plugins/<pack>/CATALOG.md    — pack-facing catalog, installed together with the pack
//
// The per-pack catalog matters because the root INDEX.md is NOT copied when a host
// installs a single pack — an agent inside an installed pack needs a catalog it can
// actually reach.
//
// Usage: npm run build-index   (or --check to verify freshness in CI)

import fs from 'node:fs';
import path from 'node:path';
import { ROOT, read_packs, skill_dirs, parse_skill_md, CATEGORIES } from './lib.mjs';

const TITLES = {
    'operations': 'Operations — the vendor-neutral SDR contract',
    'strategy': 'Strategy — playbooks and planning',
    'protection': 'Protection — guardrails and approval boundaries',
    'execution': 'Execution — driving the Reply platform',
    'runtime': 'Runtime — durable long-running work',
    'user-knowledge': 'User knowledge — personal and org memory',
};

const cell = (s) => String(s ?? '').replace(/\|/g, '\\|').replace(/\s+/g, ' ').trim();

const registry = read_packs();
const check = process.argv.includes('--check');

// pack -> category -> rows
const skills = new Map(registry.packs.map(p => [p.name, new Map(CATEGORIES.map(c => [c, []]))]));
for (const { pack, name, dir } of skill_dirs()) {
    const { data } = parse_skill_md(path.join(dir, 'SKILL.md'));
    const md = data.metadata ?? {};
    const status = md.status === 'active' ? '' : ` · **${md.status}**`;
    const by_category = skills.get(pack);
    if (!by_category) continue; // undeclared pack — validate.mjs reports it
    (by_category.get(md.category) ?? by_category.get('operations')).push({
        name,
        description: cell(data.description),
        maturity: `${cell(md.maturity)}${status}`,
        version: cell(md.version),
    });
}

const table = (rows, link) => {
    let out = '\n| Skill | Description | Maturity | Version |\n|---|---|---|---|\n';
    out += rows.map(r => `| [${r.name}](${link(r.name)}) | ${r.description} | ${r.maturity} | ${r.version} |`).join('\n');
    return out + '\n';
};

const sections = (pack, link) => {
    let out = '';
    for (const category of CATEGORIES) {
        const rows = skills.get(pack).get(category);
        if (!rows.length) continue;
        rows.sort((a, b) => a.name.localeCompare(b.name));
        out += `\n### ${TITLES[category]}\n${table(rows, link)}`;
    }
    return out;
};

// ---------------------------------------------------------------- root INDEX.md

let index = `# Skills Index

> GENERATED by \`scripts/build-index.mjs\` — do not edit by hand. Regenerate with \`npm run build-index\`.
> One fetch gives the full catalog; frontmatter in each SKILL.md is the source of truth (ADR-0003).

Skills ship in three independently installable packs. \`ai-sdr-core\` is vendor-neutral and
depends on nothing; the other two build on it. See [docs/packs.md](docs/packs.md).
`;

for (const p of registry.packs) {
    const deps = p.dependencies.length ? p.dependencies.map(d => `\`${d}\``).join(', ') : '_none_';
    index += `\n## ${p.displayName} — \`${p.name}\` v${p.version}\n\n${p.description}\n\n**Depends on:** ${deps}\n`;
    index += sections(p.name, (name) => `plugins/${p.name}/skills/${name}/SKILL.md`);
}

// ------------------------------------------------------- per-pack CATALOG.md

const targets = [{ file: path.join(ROOT, 'INDEX.md'), text: index }];

for (const p of registry.packs) {
    const deps = p.dependencies.length ? p.dependencies.map(d => `\`${d}\``).join(', ') : '_none_';
    let out = `# ${p.displayName} — skill catalog

> GENERATED by \`scripts/build-index.mjs\` — do not edit by hand.
> Agents: this is the catalog of the skills installed with this pack. Each skill's
> frontmatter is its contract.

${p.description}

**Pack:** \`${p.name}\` v${p.version} · **Depends on:** ${deps}
`;
    out += sections(p.name, (name) => `skills/${name}/SKILL.md`);
    targets.push({ file: path.join(ROOT, 'plugins', p.name, 'CATALOG.md'), text: out });
}

const stale = [];
for (const { file, text } of targets) {
    const rel = path.relative(ROOT, file).replace(/\\/g, '/');
    if (check) {
        // Compare with line endings normalised: a CRLF working tree must not read as stale.
        const current = fs.existsSync(file) ? fs.readFileSync(file, 'utf8').replace(/\r\n/g, '\n') : '';
        if (current !== text) stale.push(rel);
    } else {
        fs.writeFileSync(file, text);
    }
}

if (check) {
    if (stale.length) {
        console.error(
            `Catalogs are stale (${stale.length}):\n${stale.map(f => `  ${f}`).join('\n')}\n` +
            'Run `npm run build-index` and commit the result.'
        );
        process.exit(1);
    }
    console.log(`Catalogs are up to date (${targets.length} files).`);
} else {
    const count = [...skills.values()].flatMap(m => [...m.values()]).flat().length;
    console.log(`Wrote ${targets.length} catalogs (${count} skills across ${registry.packs.length} packs).`);
}
