// Generates INDEX.md — the catalog of all skills grouped by category (ADR-0002).
// Usage: npm run build-index   (or --check to verify freshness in CI)

import fs from 'node:fs';
import path from 'node:path';
import { ROOT, skill_dirs, parse_skill_md, CATEGORIES } from './lib.mjs';

const TITLES = {
    'technical': 'Technical — driving the Reply platform',
    'business': 'Business — outbound methodology',
    'planning': 'Planning — goals into executable plans',
    'protection': 'Protection — operational guardrails',
    'user-knowledge': 'User knowledge — personal & org memory',
};

const cell = (s) => String(s ?? '').replace(/\|/g, '\\|').replace(/\s+/g, ' ').trim();

const rows_by_category = new Map(CATEGORIES.map(c => [c, []]));
for (const { plugin, name, dir } of skill_dirs()) {
    const { data } = parse_skill_md(path.join(dir, 'SKILL.md'));
    const md = data.metadata ?? {};
    const rel = path.posix.join('plugins', plugin, 'skills', name, 'SKILL.md');
    const status = md.status === 'active' ? '' : ` · **${md.status}**`;
    (rows_by_category.get(md.category) ?? rows_by_category.get('technical')).push({
        name,
        line: `| [${name}](${rel}) | ${cell(data.description)} | ${cell(md.maturity)}${status} | ${cell(md.version)} |`,
    });
}

let out = `# Skills Index

> GENERATED by \`scripts/build-index.mjs\` — do not edit by hand. Regenerate with \`npm run build-index\`.
> One fetch gives the full catalog; frontmatter in each SKILL.md is the source of truth (ADR-0003).
`;
for (const category of CATEGORIES) {
    const rows = rows_by_category.get(category);
    if (!rows.length) continue;
    rows.sort((a, b) => a.name.localeCompare(b.name));
    out += `\n## ${TITLES[category]}\n\n| Skill | Description | Maturity | Version |\n|---|---|---|---|\n`;
    out += rows.map(r => r.line).join('\n') + '\n';
}

const target = path.join(ROOT, 'INDEX.md');
if (process.argv.includes('--check')) {
    const current = fs.existsSync(target) ? fs.readFileSync(target, 'utf8') : '';
    if (current !== out) {
        console.error('INDEX.md is stale — run `npm run build-index` and commit the result.');
        process.exit(1);
    }
    console.log('INDEX.md is up to date.');
} else {
    fs.writeFileSync(target, out);
    console.log(`INDEX.md written (${[...rows_by_category.values()].flat().length} skills).`);
}
